### ISSUE TITLE
Warning when running example

### ISSUE THREAD

**Issue by julian-belina** [zjl9959/algviz#1]
Hello and thank you for providing Algviz,

i have installed and run the graph example. I receive the following warning at each of the subexamples:

> Warning: Could not load "C:\Programmierung\conda_environments\envs\algviz\Library\bin\gvplugin_pango.dll" - It was found, so perhaps one of its dependents was not.  Try ldd.

Still, the visualizations seem to work as expected. My Environment contains the following libaries:

> # Name                    Version                   Build  Channel
> algviz                    0.1.5              pyhd8ed1ab_0    conda-forge
> argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
> argon2-cffi-bindings      21.2.0          py310he2412df_2    conda-forge
> asttokens                 2.0.8              pyhd8ed1ab_0    conda-forge
> attrs                     22.1.0             pyh71513ae_1    conda-forge
> backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
> backports                 1.1                pyhd3eb1b0_0
> backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
> beautifulsoup4            4.11.1             pyha770c72_0    conda-forge
> bleach                    5.0.1              pyhd8ed1ab_0    conda-forge
> bzip2                     1.0.8                h8ffe710_4    conda-forge
> ca-certificates           2022.07.19           haa95532_0
> cairo                     1.16.0            h63a05c6_1001    conda-forge
> cffi                      1.15.1          py310hcbf9ad4_0    conda-forge
> colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
> debugpy                   1.6.3           py310h8a704f9_0    conda-forge
> decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
> defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
> entrypoints               0.4                pyhd8ed1ab_0    conda-forge
> executing                 1.0.0              pyhd8ed1ab_0    conda-forge
> expat                     2.4.8                h39d44d4_0    conda-forge
> flit-core                 3.7.1              pyhd8ed1ab_0    conda-forge
> font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
> font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
> font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
> font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
> fontconfig                2.14.0               hce3cb01_0    conda-forge
> fonts-conda-ecosystem     1                             0    conda-forge
> fonts-conda-forge         1                             0    conda-forge
> freetype                  2.12.1               h546665d_0    conda-forge
> fribidi                   1.0.10               h8d14728_0    conda-forge
> getopt-win32              0.1                  h8ffe710_0    conda-forge
> gettext                   0.19.8.1          ha2e2712_1008    conda-forge
> glib                      2.72.1               h7755175_0    conda-forge
> glib-tools                2.72.1               h7755175_0    conda-forge
> graphite2                 1.3.14               hd77b12b_1
> graphviz                  4.0.0                had6c3a3_0    conda-forge
> gst-plugins-base          1.18.5               he07aa86_3    conda-forge
> gstreamer                 1.18.5               hdff456e_3    conda-forge
> gts                       0.7.6                h7c369d9_2    conda-forge
> harfbuzz                  4.3.0                hda2c7e1_0
> icu                       58.2                 ha925a31_3
> importlib-metadata        4.11.4          py310h5588dad_0    conda-forge
> importlib_resources       5.9.0              pyhd8ed1ab_0    conda-forge
> ipykernel                 6.7.0           py310hbbfc1a7_0    conda-forge
> ipython                   8.4.0           py310h5588dad_0    conda-forge
> ipython_genutils          0.2.0                      py_1    conda-forge
> ipywidgets                8.0.2              pyhd8ed1ab_0    conda-forge
> jedi                      0.18.1          py310h5588dad_1    conda-forge
> jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
> jpeg                      9e                   h8ffe710_2    conda-forge
> jsonschema                4.15.0             pyhd8ed1ab_0    conda-forge
> jupyter                   1.0.0           py310h5588dad_7    conda-forge
> jupyter_client            7.3.5              pyhd8ed1ab_0    conda-forge
> jupyter_console           6.4.4              pyhd8ed1ab_0    conda-forge
> jupyter_core              4.11.1          py310h5588dad_0    conda-forge
> jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
> jupyterlab_widgets        3.0.3              pyhd8ed1ab_0    conda-forge
> lerc                      4.0.0                h63175ca_0    conda-forge
> libclang                  12.0.1          default_h81446c8_4    conda-forge
> libdeflate                1.13                 h8ffe710_0    conda-forge
> libffi                    3.4.2                h8ffe710_5    conda-forge
> libgd                     2.3.3                ha43c60c_1
> libglib                   2.72.1               h3be07f2_0    conda-forge
> libiconv                  1.16                 he774522_0    conda-forge
> libogg                    1.3.5                h2bbff1b_1
> libpng                    1.6.37               h1d00b33_4    conda-forge
> libsodium                 1.0.18               h8d14728_1    conda-forge
> libsqlite                 3.39.2               h8ffe710_1    conda-forge
> libtiff                   4.4.0                h92677e6_3    conda-forge
> libvorbis                 1.3.7                h0e60522_0    conda-forge
> libxml2                   2.9.14               hf5bbc77_4    conda-forge
> libxslt                   1.1.35               h34f844d_0    conda-forge
> libzlib                   1.2.12               h8ffe710_2    conda-forge
> lxml                      4.9.1           py310he2412df_0    conda-forge
> markupsafe                2.1.1           py310he2412df_1    conda-forge
> matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
> mistune                   2.0.4              pyhd8ed1ab_0    conda-forge
> nbclient                  0.6.7              pyhd8ed1ab_0    conda-forge
> nbconvert                 7.0.0              pyhd8ed1ab_0    conda-forge
> nbconvert-core            7.0.0              pyhd8ed1ab_0    conda-forge
> nbconvert-pandoc          7.0.0              pyhd8ed1ab_0    conda-forge
> nbformat                  5.4.0              pyhd8ed1ab_0    conda-forge
> nest-asyncio              1.5.5              pyhd8ed1ab_0    conda-forge
> notebook                  6.4.12             pyha770c72_0    conda-forge
> openssl                   3.0.5                h8ffe710_1    conda-forge
> packaging                 21.3               pyhd8ed1ab_0    conda-forge
> pandoc                    2.19.2               h57928b3_0    conda-forge
> pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
> pango                     1.50.7               h66df5b2_0    conda-forge
> parso                     0.8.3              pyhd8ed1ab_0    conda-forge
> pcre                      8.45                 h0e60522_0    conda-forge
> pickleshare               0.7.5                   py_1003    conda-forge
> pip                       22.2.2             pyhd8ed1ab_0    conda-forge
> pixman                    0.38.0            hfa6e2cd_1003    conda-forge
> pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
> prometheus_client         0.14.1             pyhd8ed1ab_0    conda-forge
> prompt-toolkit            3.0.31             pyha770c72_0    conda-forge
> prompt_toolkit            3.0.31               hd8ed1ab_0    conda-forge
> pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
> pycparser                 2.21               pyhd8ed1ab_0    conda-forge
> pygments                  2.13.0             pyhd8ed1ab_0    conda-forge
> pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
> pyqt                      5.15.4          py310h8a704f9_0    conda-forge
> pyqt5-sip                 12.9.0          py310h8a704f9_0    conda-forge
> pyrsistent                0.18.1          py310he2412df_1    conda-forge
> python                    3.10.0          hcf16a7b_3_cpython    conda-forge
> python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
> python-fastjsonschema     2.16.2          py310haa95532_0
> python-graphviz           0.19.1             pyhaef67bd_0    conda-forge
> python_abi                3.10                    2_cp310    conda-forge
> pywin32                   303             py310he2412df_0    conda-forge
> pywinpty                  2.0.7           py310h00ffb61_0    conda-forge
> pyzmq                     23.2.1          py310h73ada01_0    conda-forge
> qt-main                   5.15.2               he8e5bd7_7
> qtconsole                 5.3.2              pyhd8ed1ab_0    conda-forge
> qtconsole-base            5.3.2              pyha770c72_0    conda-forge
> qtpy                      2.2.0              pyhd8ed1ab_0    conda-forge
> send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
> setuptools                65.3.0          py310h5588dad_0    conda-forge
> sip                       6.5.1           py310h8a704f9_2    conda-forge
> six                       1.16.0             pyh6c4a22f_0    conda-forge
> soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
> sqlite                    3.39.2               h8ffe710_1    conda-forge
> stack_data                0.5.0              pyhd8ed1ab_0    conda-forge
> terminado                 0.15.0          py310h5588dad_0    conda-forge
> tinycss2                  1.1.1              pyhd8ed1ab_0    conda-forge
> tk                        8.6.12               h8ffe710_0    conda-forge
> toml                      0.10.2             pyhd8ed1ab_0    conda-forge
> tornado                   6.2             py310he2412df_0    conda-forge
> traitlets                 5.3.0              pyhd8ed1ab_0    conda-forge
> tzdata                    2022c                h191b570_0    conda-forge
> ucrt                      10.0.20348.0         h57928b3_0    conda-forge
> vc                        14.2                 hb210afc_7    conda-forge
> vs2015_runtime            14.29.30139          h890b9b1_7    conda-forge
> wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
> webencodings              0.5.1                      py_1    conda-forge
> wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
> widgetsnbextension        4.0.3              pyhd8ed1ab_0    conda-forge
> winpty                    0.4.3                         4    conda-forge
> xz                        5.2.6                h8d14728_0    conda-forge
> zeromq                    4.3.4                h0e60522_1    conda-forge
> zipp                      3.8.1              pyhd8ed1ab_0    conda-forge
> zlib                      1.2.12               h8ffe710_2    conda-forge
> zstd                      1.5.2                h7755175_4    conda-forge

I have installed it according to the proceedure described in the readme file and created a conda package from the Pypi repository. Still the warning remains independent from the installation proceedure used.

**Comment by zjl9959** [comment]
Hi @julian-belina, thank you for reporting this bug! I'm trying to reproduce this warning information. Can you please provide your conda version?

**Comment by julian-belina** [comment]
My conda version is 4.12.0

**Comment by zjl9959** [comment]
Hi @julian-belina, I can't reproduce the warning in my conda-4.12.0 environment. But I assume the warning is caused by the environment variables issue about Graphviz. Because the `gvplugin_pango.dll` is a library for Graphviz, and you can find it in `<$path_to_graphviz>/bin/`.

**Here is an optional solution that may solve your problem:**
You can add the `<$path_to_graphviz>/bin/` path into your system's environment variable. Then check if the path can be detected in your virtual environment, like this:
```bat
(algviz) C:\Users\zjl>path
PATH=C:\Program Files (x86)\Graphviz\bin;
```
