### ISSUE TITLE
安装graphviz的版本选择问题

### ISSUE THREAD

**Issue by shihuinaiii** [zjl9959/algviz#13]
**Describe the bug:**
使用当前最新版graphviz-8.1.0，运行test/run.py出现以下问题：
AttributeError: 'Digraph' object has no attribute '_repr_svg_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\John\AppData\Local\Programs\Python\Python39\lib\site-packages\graphviz\backend\execute.py", line 79, in run_check
    proc = _run_input_lines(cmd, input_lines, kwargs=kwargs)
  File "C:\Users\John\AppData\Local\Programs\Python\Python39\lib\site-packages\graphviz\backend\execute.py", line 99, in _run_input_lines
    popen = subprocess.Popen(cmd, stdin=subprocess.PIPE, **kwargs)
  File "C:\Users\John\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\John\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

** solution:**
使用graphviz-7.1.0，运行test/run.py无报错
--------------------------------------------- 
>>>> Begin <test_logger>.
>>>> OK!
>>>> End <test_logger> (2.99 ms).
---------------------------------------------
>>>> Begin <test_vector>.
>>>> OK!
>>>> End <test_vector> (16.95 ms).
---------------------------------------------
>>>> Begin <test_table>.
>>>> OK!
>>>> End <test_table> (17.94 ms).
---------------------------------------------
>>>> Begin <test_linked_list>.
>>>> OK!
>>>> End <test_linked_list> (1562.47 ms).
---------------------------------------------
>>>> Begin <test_tree>.
>>>> OK!
>>>> End <test_tree> (1735.64 ms).
---------------------------------------------
>>>> Begin <test_graph>.
>>>> OK!
>>>> End <test_graph> (1612.70 ms).
---------------------------------------------
>>>> Begin <test_map>.
>>>> OK!
>>>> End <test_map> (692.49 ms).
---------------------------------------------
>>>> Begin <test_regression>.
>>>> OK!
>>>> End <test_regression> (0.50 ms).
*********************************************
Congratulations, everything is OK !!!
*********************************************

**Comment by zjl9959** [comment]
感谢您报告这个问题，可能是最新版 graphviz 更新了 API 接口，导致软件出现了兼容性问题。
我会在下个版本修复该问题，您可以暂时用 graphviz-7.1.0，它们在功能上是没有什么差别的。

**Comment by zjl9959** [comment]
已在 0.3.1 版本解决该问题，请使用：`pip install --upgrade algviz` 更新安装包即可！
