### ISSUE TITLE
grahviz版本报错

### ISSUE THREAD

**Issue by Extra-GNU** [zjl9959/algviz#14]
你好，我使用创建二叉树的功能时，出现了如下错误，'Digraph' object has no attribute '_repr_svg_'，
![image](https://github.com/zjl9959/algviz/assets/75910024/f6a75127-a4d5-43a6-ac49-fb4511541855)
并显示不支持的grahivz版本
![image](https://github.com/zjl9959/algviz/assets/75910024/9b88df65-09d6-4e55-adac-1ab51252f5c7)
我尝试了更新版本
![image](https://github.com/zjl9959/algviz/assets/75910024/79854c9c-272b-40f9-9059-090926970115)
但是依然出错，请问如何解决呢？

**Comment by zjl9959** [comment]
你好 @Extra-GNU，这个报错可能是没有安装最新的 algviz 导致的，麻烦使用：`pip install --upgrade algviz` 更新一下试试。另外，关于 graphviz 版本的选择，暂时请使用 `graphviz-7.1.0` （*原因：相关 issue：#13*），这是 graphviz 安装包的[下载链接](https://graphviz.org/download/)，谢谢！

**Comment by zjl9959** [comment]
已在 0.3.1 版本解决该问题，请使用：`pip install --upgrade algviz` 更新安装包即可！
