### ISSUE TITLE
Multi-Child Tree Display Does Not Update

### ISSUE THREAD

**Issue by lucasmurphyy** [zjl9959/algviz#6]
Sample code from the tutorial recreates the bug:
```
tree_info = {
    0: [1, 2, 3],   # Node0 has child nodes: 1, 2, 3.
    1: [4, 5],      # Node1 has child nodes: 4, 5.
    2: [6]          # Node2 has child node: 6.
}
nodes_label = {
    0: 'root',      # Set the display name of node0 as 'root'.
    3: 'n3'         # Set the display name of node3 as 'n3'.
}
root2 = algviz.parseTree(tree_info, nodes_label)
tree = viz.createGraph(data=root2, name="Tree")
viz.display()
```
```
# Visit all the child nodes in root2 and mark them.
for child in root2.children():
    tree.markNode(algviz.color_red, child)
    viz.display(1.0)
tree_node3 = root2.childAt(2)           # Record node3.
tree_node3.add(algviz.TreeNode(8))      # Add a new node8 for node3.
viz.display()
tree_node3.add(algviz.TreeNode(7), 0)   # Add a new node7 for node3.
viz.display()
root2.removeAt(1)                       # Remove the subtree 'node2->node6' of the root node.
viz.display()
```

The first cell correctly displays the tree when ran. The second cell does not update. It appears that after one or two 'display()' calls the graph no longer visually updates (however when I checked, the tree object was still having new nodes added).

**Test enviroment:**
 - OS: Mac OS
 - Algviz version: 0.2.2
 - Jupyter notebook version:
 Version: 1.76.1 (Universal)
Commit: 5e805b79fcb6ba4c2d23712967df89a089da575b
Date: 2023-03-08T16:32:09.831Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: Yes

**Comment by zjl9959** [comment]
@lucasmurphyy Thank you for providing detailed information about this bug! I reproduced the problem that you described. It seems that the tree node status change wasn't detected when the animation updating. I will try to fix it in the next release version.

**Comment by lucasmurphyy** [comment]
Thanks for the quick response! Yeah I’ve been looking for a library to demonstrate the building and searching of a trie data structure and this repo is absolutely leagues ahead of anything else I have found. Could I also leave another suggestion? It would be useful to have a way to rename node values. For my trie example I would like to have count values of each node update as the trie is being constructed, however it seems that the value you set when you add a node cannot be changed.

Lucas Murphy
Graduate Data Scientist | DCI: Affordability - Data Innovation
Experian | Floor 3.01 | McLellan Works | 274 Sauchiehall | G2 3EH
www.experian.com<http://www.experian.com/>
***@***.***<http://www.experian.com/>


From: zjl9959 ***@***.***>
Date: Thursday, 16 March 2023 at 07:33
To: zjl9959/algviz ***@***.***>
Cc: Murphy, Lucas ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [zjl9959/algviz] Multi-Child Tree Display Does Not Update (Issue #6)
External email: Do not click the links. Verify legitimacy before taking action.

@lucasmurphyy<https://urldefense.com/v3/__https:/github.com/lucasmurphyy__;!!MfzFaTml5A!lYm63a04sGyNqcmWbWgSKF7pSFL7RItFBvUVc_PREOtqonrlulF20xfe2OIVILtQCV2dfKDQAEXw4NxAaSqzBA7EogoJ$> Thank you for providing detailed information about this bug! I reproduced the problem that you described. It seems that the tree node status change wasn't detected when the animation updating. I will try to fix it in the next release version.

**Comment by zjl9959** [comment]
@lucasmurphyy I'm glad to hear that this repo can help to solve your problems.
1. About the animation doesn't update issue, I find the root cause is the compatibility issue with jupyter notebook. I can reproduce this bug with VSCode + Jupyter_extension_v2023.2.1200692131. But I can not reproduce this bug with Anaconda + JupyterNotebook_v6.5.2 + Chrome_111.0.5563.65. I will improve the compatibility in the next release version. **But for a quick fix, you can roll back your jupyter notebook (before 2022.10.1) or try the Anaconda + JupytherNotebook environment.**
2. About the "rename node values" suggestion, algviz has already supported this feature. You can simply assign a new name to the `node.val` like this:
``` python
node.val="a:3"
viz.display()
node.val="a:4"
viz.display()
```

If you meet any other problems when using algviz, please feel free to pin me! 😊

**Comment by zjl9959** [comment]
This is the related issue about the VSCode jupyter extension.
https://github.com/microsoft/vscode-jupyter/issues/13105

**Comment by zjl9959** [comment]
The latest vscode jupyter extension(`v2023.3.1000892223` or later) has fixed the issue https://github.com/microsoft/vscode-jupyter/issues/13105. You can open this issue again if the problem still exists.

**Comment by lucasmurphyy** [comment]
Thanks for the help!
